name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Get list of modified services
        id: changes
        run: |
          # Get the list of modified directories (services)
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/gradlew' | cut -d/ -f1 | sort -u)
          echo "Modified services: $changes"
          echo "::set-output name=changed-services::$changes"

      - name: Build changed services
        run: |
          # Build each changed service
          for service in ${{ steps.changes.outputs.changed-services }}; do
            echo "Building service: $service"
            if [ -f "$service/gradlew" ]; then
              chmod +x $service/gradlew
              $service/gradlew build -x test -p $service
            fi
          done
